name: Daily

on:
  schedule:
    - cron: '0 23 * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Install dependencies
      run: |
        pip3 install playwright
        playwright install chromium

    - name: Login
      run: |
        python3 main.py
      env:
        COOKIES: ${{ secrets.COOKIES }}
